### PR TITLE
Principal part edit of corrumpo

### PR DESCRIPTION
**Pull request by shomauno**
Changed "corrapi" to "corrupi" in principal parts of corrumpo.

### CODE REVIEW

**Comment by lcerrato** [comment]
Hi, 
Thanks for this.
I have a logged email on this same word. 
The usual workflow is to fix typos submitted via email in batches. Due to the large number of lexica related reports and the current workflow focusing on primary texts, I have been holding off on these fixes.
I will check the source at the next opportunity.

**Comment by shomauno** [comment]
Alright, thank you!
This is my first time with GitHub, so I was trying to see how to edit files using SourceTree and the command line.

**Comment by lcerrato** [comment]
cross reference #9

**Comment by lcerrato** [comment]
There's a conflict with the Latin. I want to further investigate.

**Comment by lcerrato** [comment]
@shomauno Please check that the latest version of the Perseus file incorporates your changes.

**Comment by shomauno** [comment]
Yes, both are correct now.

**Pull request closed without merging**
