### PR TITLE
Some minor corrections

### PR DESCRIPTION
**Pull request by adiel-mittmann**

### CODE REVIEW

**Comment by lcerrato** [comment]
Thank you!

**Comment by adiel-mittmann** [comment]
Hi, @lcerrato, will Middle Liddell be imported into a GitHub repository too?  I have been making many small corrections to the file I obtained from Perseus: https://github.com/adiel-mittmann/middle-liddell.

**Comment by lcerrato** [comment]
Hi @adiel-mittmann,

There is a version of the ML here:
https://github.com/PerseusDL/canonical-pdlrefwk/tree/master/data/viaf66541464/001

I don't know the extent of the conversion status of the file — it has some beta code but beyond that, it's not documented what other changes were made or by whom. It appears to have the most recent changes in our Perseus 4 source file, but other than that, I don't have a history on the file.

I'm not sure that the team that was working on these files were even aware of this repo at the time the files were moved into canonical-pdlrefwk. At this point, I am going to leave it where it is. If you'd rather have the beta code version in this repo, I'm happy to add that here.

**Comment by adiel-mittmann** [comment]
I didn't know it was already available in a GitHub repo.  I did search for it, but couldn't find it.

Are changes to that file welcome?  I only found beta code in the `@key` attributes — should it be converted to unicode?  Is there any documentation on how such files should be encoded?

**Pull request merged**
