### PR TITLE
Some more fixes for LS

### PR DESCRIPTION
**Pull request by nkprasad12**
This PR has the following notable changes
- Entries in the text where there is a standard author abbreviation followed by a standard work abbreviation for that author, but no `<author>` or `<bibl>` tagging have been fixed [Approx 2000 entries modified]
- The entry for `reno` has been split (the scan shows 2 entries for reno1 and reno2, but the digitization only had one entry for reno)
- Added a correction in `n895` (`admissor`) from Cic. Div. to Civ. Dei
  - Old: `<author>Aug.</author> Cic. Div. 7, 3`
  - New: `<author>Aug.</author> <reg><sic>Cic. Div.</sic><corr>Civ. Dei</corr></reg> 7, 3`
  - This is because Cic. Div. only has two books (and the Augustine doesn't make sense in that context), while Civ. Dei *does* have a 7th book and in addition the cited word `admissor` shows up in that passage exactly as expected.

There are also minor fixes to tagging (some `<author>id.</author>` tags that were part of the word prior, e.g. `aliqu<author>id.</author>` have been removed, etc...) and some spacing (split words across a column break, e.g. `Has drubal` -> `Hasdrubal`).

### CODE REVIEW

**Comment by nkprasad12** [comment]
Hi @lcerrato - please let me know if there are any changes I should make here

**Comment by lcerrato** [comment]
@nkprasad12 
Sorry--another project intervened and I am now fighting an illness.

**Comment by lcerrato** [comment]
I'm conflicted on the bibl/author revisions. One the one hand, there are many untagged or incorrect citations, but on the other, I think a running list of missed patterns might be the best approach for another automated round of citation capture. All of these need to be remapped and revisited in the new environment. (One early task was to have students manually check all invalid refs: this should be done again in the context of all of the newer text additions.)

I worry that some of this new markup might make further automated citation fishing harder rather than easier. A list of uncaptured citations might be the better approach? 

I don't think it's worth it to roll this back since it is a lot of stuff, but I think I may need to consider further refinements to some of this in order to make coded capture possible for future editors or contributors.

Some thoughts from a first glance:

I do not think that `<bibl><author>Serv.</author> ad <author>Verg.</author> A. 7, 647</bibl> ` would work under the old system, where only one author per bibl is expected. I believe the old citation fishing code expected one author and one work.
(That may not be applicable or desirable moving forward.) Probably not an issue if the pattern is consistent. (

It also gets back to the categorization of Servius: is it a commentary, an edition, etc? Is the title of this work actually "ad Verg. A."? one could make the case for that. 

Some missing titles. Not every bibl will have one, but I could do a search to identify ones that do not just to see if there is any pattern there.

I also see things like this:-
`<bibl><author>Aus.</author> Idyll.</bibl> praef. 11.` where the bibl should probably be `<bibl><author>Aus.</author> <work>Idyll.</work>  praef. 11.</bibl>` and `<bibl><author>Verg.</author> A.</bibl>, 6, 295 al.` where the digits are outside of the close tag. So the pattern matching would fail to apply the citation here. See also `<bibl><author>Frontin.</author> Aquaed.</bibl> 10; 69`  

Prematurely closing the bibl introduces a new issue that needs to be checked and fixed whereas `Frontin. Aquaed. 10; 69`  represents an author/ work pattern that we can identify and fix and use as the basis of another fishing pass.

I also see  Pseudo-`<bibl><author>Quint.</author> Decl.</bibl>` where the "Pseudo" was omitted from the author.

Unfortunately, there are no students available to assist with this: I can see a few distinct ways of trying to improve what is there and refine it further.

**Comment by nkprasad12** [comment]
Thanks for the detailed comments, and I hope you're recovering well from your illness :) 

Please let me know your thoughts on the following plan:

[1] Re: Issue of one `author` per `bibl` 

I can simply remove any second authors I added inside a `bibl`, or maybe add a new tag for that so they're marked for future revision, whatever seems better to you.

[2] Re: Issue of missing titles

I have gone through the preface and picked up abbreviations and titles listed there (and augmented those with obvious variants that are not listed there), but if there are big categories I am missing (e.g. if y'all at Perseus have your own improved list?) I am very happy to handle those as well.

[3] Re: Issue of digits outside the `bibl` close tag

I will update my script to make sure that trailing digits are included in the bibl tag. I will play around with things like `praef.` where it is not a digit but should also be include. My plan is to try an exhaustive search: whenever we have pattern like `[author] [work] [word.] [optional other word] [digits] [optional more digits]` etc... I can manually review and build up some list that ought to be included here, as I imagine it is probably not too long of a list (variants of prologue, epilogue, preface, appendix, etc...).

**Comment by lcerrato** [comment]
@nkprasad12 
Still battling a cold after my procedure—thanks for the concern. I'll muddle through.
This sounds awesome!  I think the Servius should have the "ad Verg. A." as the title. Do you agree? Beyond that, I think the pattern should work and be a substantial improvement in any case.
Beyond that, we do have lists—so many lists. My colleague @AlisonBabeu can point you there. I'm not sure if they would help. 
I've always thought these big ref works have a system they employ consistently 90-95% of the time and then you see these errors or deviations that pop up. But we do what we can.

**Comment by lcerrato** [comment]
@nkprasad12 
I'm going to approve this. Please let us know if you want any lists or other info before another pass of citation capture.

**Pull request merged**
